FROM python:3.11-slim-buster

ENV PYENV_SHELL=/bin/bash

RUN set -ex; \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential && \
    pip install --no-cache-dir --upgrade pip && \
    pip install pipenv && \
    mkdir -p /package

WORKDIR /package

ADD Pipfile Pipfile.lock /package/

RUN pipenv sync

ADD . /package

ENTRYPOINT ["/bin/bash"]

CMD ["-c", "pipenv shell"]